timm==0.3.2
-e ./i2i_mage/
-e ./i2i_clean-fid/
albumentations==1.3.1
opencv-python==4.9.0.80
pudb==2024.1
imageio==2.33.1
imageio-ffmpeg==0.4.9
pytorch-lightning==2.1.3
omegaconf==2.3.0
test-tube>=0.7.5
streamlit>=1.30.0
einops==0.7.0
more-itertools>=8.0.0
transformers==4.37.2
tensorboardX>=1.14
open-clip-torch==2.20.0
matplotlib>=3.7
scipy==1.11.1
